<?php
/* Author: Massimiliano Adamo, and others */

$labels = array();
$labels['markreadfolder'] = 'Marca tutto come letto';
$labels['collapseall'] = 'Compatta tutte le cartelle';
$labels['expandall'] = 'Espandi tutte le cartelle';
$labels['addcontactto'] = 'Aggiungi contatto a Destinatario';
$labels['addcontactcc'] = 'Aggiungi contatto a Cc';
$labels['addcontactbcc'] = 'Aggiungi contatto a Bcc';

$messages = array();

?>
